# Generated by Django 4.2.1 on 2023-05-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profilepicture_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
