# Generated by Django 4.1.7 on 2023-04-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_id'),
        ('tasks', '0003_rename_name_task_title'),
    ]

    operations = [
    ]
