# Generated by Django 4.1.7 on 2023-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_end_time_alter_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
