# Generated by Django 4.2.1 on 2023-05-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_plan_end_date_alter_plan_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['start_date', 'start_time']},
        ),
    ]
